apiVersion: apps/v1
kind: Deployment
metadata:
  name: w0q-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w0q
  template:
    metadata:
      labels:
        app: w0q
    spec:
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  postgres-secret-config
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-storage
      - name: w0q
        image: webbaum/w0q:latest
        volumeMounts:
          - name: volume-woq
            mountPath: /data
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "50m"
      
      volumes:
      - name: volume-woq
        hostPath:
         path: /opt/woq
      - name: postgres-pv-storage
        persistentVolumeClaim: 
          claimName: postgres-pv-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: w0q
spec:
  type: NodePort
  selector:
    app: w0q
  ports:
    - port: 8080