apiVersion: apps/v1
kind: Deployment
metadata:
  name: w0q-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w0q-postgres
  template:
    metadata:
      labels:
        app: w0q-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  postgres-secret-config
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-storage
    
      volumes:
      - name: postgres-pv-storage
        persistentVolumeClaim: 
          claimName: postgres-pv-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: w0q-postgres
spec:
  type: NodePort
  selector:
    app: w0q-postgres
  ports:
    - port: 5432